# Generated by Django 4.0.3 on 2022-10-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvo',
            name='updated',
        ),
    ]
