# Generated by Django 4.0.3 on 2022-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0002_remove_accountvo_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
